export interface TextureEntry {
  name: string;
  frames: number;
  frametime: number;
  interpolate: boolean;
  opaque: boolean;
}

function tex(
  name: string,
  frames = 1,
  frametime = 1,
  interpolate = false,
  opaque = true,
): TextureEntry {
  return { name, frames, frametime, interpolate, opaque };
}

function anim(
  name: string,
  frames: number,
  frametime = 1,
  interpolate = false,
  opaque = true,
): TextureEntry {
  return { name, frames, frametime, interpolate, opaque };
}

// === Minecraft Block Textures List ===
export const BLOCK_TEXTURES: TextureEntry[] = [
  // === Stone ===
  tex("stone"),
  tex("stone_bricks"),
  tex("cracked_stone_bricks"),
  tex("chiseled_stone_bricks"),
  tex("mossy_stone_bricks"),
  tex("cobblestone"),
  tex("mossy_cobblestone"),
  tex("smooth_stone"),
  tex("smooth_stone_slab_side"),

  // === Dirt / Grass ===
  tex("dirt"),
  tex("coarse_dirt"),
  tex("rooted_dirt"),
  tex("grass_block_top"),
  tex("grass_block_side"),
  tex("grass_block_side_overlay", 1, 1, false, false), // transparent overlay
  tex("grass_block_snow"),
  tex("podzol_top"),
  tex("podzol_side"),
  tex("mycelium_top"),
  tex("mycelium_side"),

  // === Sand / gravel ===
  tex("sand"),
  tex("red_sand"),
  tex("gravel"),
  tex("soul_sand"),
  tex("soul_soil"),

  // === Wood logs (all 6 wood types × top/side) ===
  tex("oak_log"),
  tex("oak_log_top"),
  tex("spruce_log"),
  tex("spruce_log_top"),
  tex("birch_log"),
  tex("birch_log_top"),
  tex("jungle_log"),
  tex("jungle_log_top"),
  tex("acacia_log"),
  tex("acacia_log_top"),
  tex("dark_oak_log"),
  tex("dark_oak_log_top"),
  tex("mangrove_log"),
  tex("mangrove_log_top"),
  tex("cherry_log"),
  tex("cherry_log_top"),
//   tex("crimson_stem"),
//   tex("crimson_stem_top"),
//   tex("warped_stem"),
//   tex("warped_stem_top"),
//   tex("stripped_oak_log"),
//   tex("stripped_oak_log_top"),
//   tex("stripped_spruce_log"),
//   tex("stripped_spruce_log_top"),
//   tex("stripped_birch_log"),
//   tex("stripped_birch_log_top"),
//   tex("stripped_jungle_log"),
//   tex("stripped_jungle_log_top"),
//   tex("stripped_acacia_log"),
//   tex("stripped_acacia_log_top"),
//   tex("stripped_dark_oak_log"),
//   tex("stripped_dark_oak_log_top"),
//   tex("stripped_mangrove_log"),
//   tex("stripped_mangrove_log_top"),
//   tex("stripped_cherry_log"),
//   tex("stripped_cherry_log_top"),
//   tex("stripped_crimson_stem"),
//   tex("stripped_crimson_stem_top"),
//   tex("stripped_warped_stem"),
//   tex("stripped_warped_stem_top"),

  // === Wood planks ===
  tex("oak_planks"),
  tex("spruce_planks"),
  tex("birch_planks"),
  tex("jungle_planks"),
  tex("acacia_planks"),
  tex("dark_oak_planks"),
  tex("mangrove_planks"),
  tex("cherry_planks"),
  tex("crimson_planks"),
  tex("warped_planks"),
  tex("bamboo_planks"),
  tex("bamboo_mosaic"),

  // === Leaves ===
  tex("oak_leaves", 1, 1, false, false),
  tex("spruce_leaves", 1, 1, false, false),
  tex("birch_leaves", 1, 1, false, false),
  tex("jungle_leaves", 1, 1, false, false),
  tex("acacia_leaves", 1, 1, false, false),
  tex("dark_oak_leaves", 1, 1, false, false),
  tex("mangrove_leaves", 1, 1, false, false),
  tex("cherry_leaves", 1, 1, false, false),
  tex("azalea_leaves", 1, 1, false, false),
  tex("azalea_leaves_flowers", 1, 1, false, false),

  // === Ores ===
  tex("coal_ore"),
  tex("iron_ore"),
  tex("copper_ore"),
  tex("gold_ore"),
  tex("redstone_ore"),
  tex("emerald_ore"),
  tex("lapis_ore"),
  tex("diamond_ore"),
  tex("deepslate_coal_ore"),
  tex("deepslate_iron_ore"),
  tex("deepslate_copper_ore"),
  tex("deepslate_gold_ore"),
  tex("deepslate_redstone_ore"),
  tex("deepslate_emerald_ore"),
  tex("deepslate_lapis_ore"),
  tex("deepslate_diamond_ore"),
  tex("nether_gold_ore"),
  tex("nether_quartz_ore"),
  tex("ancient_debris_side"),
  tex("ancient_debris_top"),

  // === Deepslate ===
  tex("deepslate"),
  tex("deepslate_top"),
  tex("cobbled_deepslate"),
  tex("polished_deepslate"),
  tex("deepslate_bricks"),
  tex("cracked_deepslate_bricks"),
  tex("deepslate_tiles"),
  tex("cracked_deepslate_tiles"),
  tex("chiseled_deepslate"),
  tex("reinforced_deepslate"),

  // === Mineral blocks ===
  tex("coal_block"),
  tex("iron_block"),
  tex("copper_block"),
  tex("exposed_copper"),
  tex("weathered_copper"),
  tex("oxidized_copper"),
  tex("cut_copper"),
  tex("exposed_cut_copper"),
  tex("weathered_cut_copper"),
  tex("oxidized_cut_copper"),
  tex("gold_block"),
  tex("redstone_block"),
  tex("emerald_block"),
  tex("lapis_block"),
  tex("diamond_block"),
  tex("netherite_block"),
  tex("raw_iron_block"),
  tex("raw_copper_block"),
  tex("raw_gold_block"),
  tex("amethyst_block"),
  tex("budding_amethyst"),

  // === Nether ===
//   tex("netherrack"),
//   tex("nether_bricks"),
//   tex("cracked_nether_bricks"),
//   tex("chiseled_nether_bricks"),
//   tex("red_nether_bricks"),
//   tex("basalt_side"),
//   tex("basalt_top"),
//   tex("polished_basalt_side"),
//   tex("polished_basalt_top"),
//   tex("smooth_basalt"),
//   tex("blackstone"),
//   tex("blackstone_top"),
//   tex("gilded_blackstone"),
//   tex("polished_blackstone"),
//   tex("polished_blackstone_bricks"),
//   tex("cracked_polished_blackstone_bricks"),
//   tex("chiseled_polished_blackstone"),
//   tex("nether_wart_block"),
//   tex("warped_wart_block"),
//   tex("shroomlight"),
//   tex("glowstone"),
//   tex("magma", 4, 2, false), // animated glow
//   tex("quartz_block_side"),
//   tex("quartz_block_top"),
//   tex("quartz_block_bottom"),
//   tex("chiseled_quartz_block"),
//   tex("chiseled_quartz_block_top"),
//   tex("smooth_quartz"),
//   tex("quartz_bricks"),

  // === End ===
//   tex("end_stone"),
//   tex("end_stone_bricks"),
//   tex("purpur_block"),
//   tex("purpur_pillar"),
//   tex("purpur_pillar_top"),
//   tex("end_portal_frame_top"),
//   tex("end_portal_frame_side"),
//   tex("chorus_flower", 1, 1, false, false),

  // === Fluids (animated) ===
  anim("water_still", 32, 1, true, false), // 16×512 sprite sheet
  anim("water_flow", 32, 1, true, false), // 32×1024 (flowing UV scroll)
  anim("water_overlay", 16, 1, true, false), // underwater overlay
  anim("lava_still", 20, 1, true), // 16×320
  anim("lava_flow", 16, 1, true), // 32×512

  // === Glass / transparent ===
//   tex("glass", 1, 1, false, false),
//   tex("glass_pane_top", 1, 1, false, false),
//   tex("white_stained_glass", 1, 1, false, false),
//   tex("orange_stained_glass", 1, 1, false, false),
//   tex("magenta_stained_glass", 1, 1, false, false),
//   tex("light_blue_stained_glass", 1, 1, false, false),
//   tex("yellow_stained_glass", 1, 1, false, false),
//   tex("lime_stained_glass", 1, 1, false, false),
//   tex("pink_stained_glass", 1, 1, false, false),
//   tex("gray_stained_glass", 1, 1, false, false),
//   tex("light_gray_stained_glass", 1, 1, false, false),
//   tex("cyan_stained_glass", 1, 1, false, false),
//   tex("purple_stained_glass", 1, 1, false, false),
//   tex("blue_stained_glass", 1, 1, false, false),
//   tex("brown_stained_glass", 1, 1, false, false),
//   tex("green_stained_glass", 1, 1, false, false),
//   tex("red_stained_glass", 1, 1, false, false),
//   tex("black_stained_glass", 1, 1, false, false),

  // === Ice ===
//   tex("ice", 1, 1, false, false),
//   tex("blue_ice"),
//   tex("packed_ice"),
//   tex("frosted_ice_0", 1, 1, false, false),
//   tex("frosted_ice_1", 1, 1, false, false),
//   tex("frosted_ice_2", 1, 1, false, false),
//   tex("frosted_ice_3", 1, 1, false, false),

  // === Wool / terracotta / concrete ===
//   ...[
//     "white",
//     "orange",
//     "magenta",
//     "light_blue",
//     "yellow",
//     "lime",
//     "pink",
//     "gray",
//     "light_gray",
//     "cyan",
//     "purple",
//     "blue",
//     "brown",
//     "green",
//     "red",
//     "black",
//   ].flatMap((c) => [
//     tex(`${c}_wool`),
//     tex(`${c}_terracotta`),
//     tex(`${c}_concrete`),
//     tex(`${c}_concrete_powder`),
//     tex(`${c}_glazed_terracotta`),
//   ]),
//   tex("terracotta"),

  // === Functional blocks ===
  tex("crafting_table_top"),
  tex("crafting_table_side"),
  tex("crafting_table_front"),
  tex("furnace_front"),
  tex("furnace_front_on", 4, 1, false), // animated when active
  tex("furnace_side"),
  tex("furnace_top"),
  tex("blast_furnace_front"),
  tex("blast_furnace_front_on", 4, 1, false),
  tex("blast_furnace_side"),
  tex("blast_furnace_top"),
  tex("smoker_front"),
  tex("smoker_front_on", 4, 1, false),
  tex("smoker_side"),
  tex("smoker_top"),
  tex("smoker_bottom"),
  tex("chest_front"),
  tex("chest_side"),
  tex("chest_top"),
  tex("trapped_chest_front"),
  tex("trapped_chest_side"),
  tex("trapped_chest_top"),
  tex("ender_chest_front"),
  tex("ender_chest_side"),
  tex("ender_chest_top"),
  tex("bookshelf"),
  tex("chiseled_bookshelf"),
  tex("chiseled_bookshelf_top"),
  tex("chiseled_bookshelf_occupied"),
  tex("lectern_front"),
  tex("lectern_sides"),
  tex("lectern_top"),
  tex("lectern_base"),
  tex("tnt_side"),
  tex("tnt_top"),
  tex("tnt_bottom"),
  tex("dispenser_front"),
  tex("dispenser_front_vertical"),
  tex("dropper_front"),
  tex("dropper_front_vertical"),
  tex("piston_top"),
  tex("piston_top_sticky"),
  tex("piston_side"),
  tex("piston_bottom"),
  tex("piston_inner"),

  // === Redstone ===
//   tex("redstone_lamp"),
//   tex("redstone_lamp_on"),
//   tex("repeater"),
//   tex("repeater_on"),
//   tex("comparator"),
//   tex("comparator_on"),
//   tex("observer_front"),
//   tex("observer_front_lit"),
//   tex("observer_back"),
//   tex("observer_side"),
//   tex("observer_top"),
//   tex("target_top"),
//   tex("target_side"),
//   tex("daylight_detector_top"),
//   tex("daylight_detector_inverted_top"),
//   tex("daylight_detector_side"),
//   tex("command_block_front"),
//   tex("command_block_back"),
//   tex("command_block_side"),
//   tex("command_block_conditional"),

  // === Lighting ===
//   tex("torch"),
//   tex("soul_torch"),
//   tex("lantern"),
//   tex("soul_lantern"),
//   tex("sea_lantern", 4, 1, true), // animated
//   anim("fire_0", 32, 1, false, false), // fire animation frames
//   anim("fire_1", 32, 1, false, false),
//   anim("soul_fire_0", 16, 1, false, false),
//   anim("soul_fire_1", 16, 1, false, false),
//   tex("campfire_fire", 1, 1, false, false),
//   tex("soul_campfire_fire", 1, 1, false, false),
//   tex("campfire_log"),
//   tex("campfire_log_lit"),

  // === Plants / flora (non-cube, transparent) ===
//   tex("grass", 1, 1, false, false),
//   tex("fern", 1, 1, false, false),
//   tex("dead_bush", 1, 1, false, false),
//   tex("dandelion", 1, 1, false, false),
//   tex("poppy", 1, 1, false, false),
//   tex("blue_orchid", 1, 1, false, false),
//   tex("allium", 1, 1, false, false),
//   tex("azure_bluet", 1, 1, false, false),
//   tex("red_tulip", 1, 1, false, false),
//   tex("orange_tulip", 1, 1, false, false),
//   tex("white_tulip", 1, 1, false, false),
//   tex("pink_tulip", 1, 1, false, false),
//   tex("oxeye_daisy", 1, 1, false, false),
//   tex("cornflower", 1, 1, false, false),
//   tex("lily_of_the_valley", 1, 1, false, false),
//   tex("wither_rose", 1, 1, false, false),
//   tex("sunflower_front", 1, 1, false, false),
//   tex("sunflower_back", 1, 1, false, false),
//   tex("sunflower_top", 1, 1, false, false),
//   tex("sunflower_bottom", 1, 1, false, false),
//   tex("lilac_top", 1, 1, false, false),
//   tex("lilac_bottom", 1, 1, false, false),
//   tex("rose_bush_top", 1, 1, false, false),
//   tex("rose_bush_bottom", 1, 1, false, false),
//   tex("peony_top", 1, 1, false, false),
//   tex("peony_bottom", 1, 1, false, false),
//   tex("tall_grass_top", 1, 1, false, false),
//   tex("tall_grass_bottom", 1, 1, false, false),
//   tex("large_fern_top", 1, 1, false, false),
//   tex("large_fern_bottom", 1, 1, false, false),
//   tex("sugar_cane", 1, 1, false, false),
//   tex("bamboo_stalk", 1, 1, false, false),
//   tex("bamboo_small_leaves", 1, 1, false, false),
//   tex("bamboo_large_leaves", 1, 1, false, false),
//   tex("cactus_top", 1, 1, false, false),
//   tex("cactus_side", 1, 1, false, false),
//   tex("cactus_bottom"),
//   tex("lily_pad", 1, 1, false, false),
//   tex("sea_pickle", 1, 1, false, false),
//   tex("kelp", 16, 2, true, false), // animated
//   tex("kelp_plant", 16, 2, true, false),
//   tex("seagrass", 8, 2, true, false),
//   tex("tall_seagrass_top", 8, 2, true, false),
//   tex("tall_seagrass_bottom", 8, 2, true, false),
//   tex("glow_lichen", 1, 1, false, false),
//   tex("hanging_roots", 1, 1, false, false),

  // === Mushrooms ===
//   tex("brown_mushroom"),
//   tex("red_mushroom"),
//   tex("brown_mushroom_block"),
//   tex("red_mushroom_block"),
//   tex("mushroom_stem"),

  // === Crops ===
//   tex("wheat_stage0", 1, 1, false, false),
//   tex("wheat_stage1", 1, 1, false, false),
//   tex("wheat_stage2", 1, 1, false, false),
//   tex("wheat_stage3", 1, 1, false, false),
//   tex("wheat_stage4", 1, 1, false, false),
//   tex("wheat_stage5", 1, 1, false, false),
//   tex("wheat_stage6", 1, 1, false, false),
//   tex("wheat_stage7", 1, 1, false, false),
//   tex("carrots_stage0", 1, 1, false, false),
//   tex("carrots_stage1", 1, 1, false, false),
//   tex("carrots_stage2", 1, 1, false, false),
//   tex("carrots_stage3", 1, 1, false, false),
//   tex("potatoes_stage0", 1, 1, false, false),
//   tex("potatoes_stage1", 1, 1, false, false),
//   tex("potatoes_stage2", 1, 1, false, false),
//   tex("potatoes_stage3", 1, 1, false, false),
//   tex("beetroots_stage0", 1, 1, false, false),
//   tex("beetroots_stage1", 1, 1, false, false),
//   tex("beetroots_stage2", 1, 1, false, false),
//   tex("beetroots_stage3", 1, 1, false, false),
//   tex("melon_side"),
//   tex("melon_top"),
//   tex("pumpkin_side"),
//   tex("pumpkin_top"),
//   tex("carved_pumpkin"),
//   tex("jack_o_lantern"),
//   tex("attached_melon_stem", 1, 1, false, false),
//   tex("attached_pumpkin_stem", 1, 1, false, false),
//   tex("melon_stem", 1, 1, false, false),
//   tex("pumpkin_stem", 1, 1, false, false),

  // === Bedrock / Special ===
//   tex("bedrock"),
//   tex("barrier", 1, 1, false, false),
//   tex("structure_block"),
//   tex("jigsaw_top"),
//   tex("jigsaw_side"),
//   tex("jigsaw_bottom"),
//   tex("spawner"),

  // === Misc ===
//   tex("sponge"),
//   tex("wet_sponge"),
//   tex("hay_block_side"),
//   tex("hay_block_top"),
//   tex("bone_block_side"),
//   tex("bone_block_top"),
//   tex("dried_kelp_side"),
//   tex("dried_kelp_top"),
//   tex("dried_kelp_bottom"),
//   tex("snow"),
//   tex("powder_snow"),
//   tex("clay"),
//   tex("dirt_path_top"),
//   tex("dirt_path_side"),
//   tex("farmland"),
//   tex("farmland_moist"),
//   tex("moss_block"),
//   tex("moss_carpet"),
//   tex("obsidian"),
//   tex("crying_obsidian", 12, 1, true), // animated glow
//   tex("respawn_anchor_top"),
//   tex("respawn_anchor_top_off"),
//   anim("respawn_anchor_side0", 8, 1, true),
//   anim("respawn_anchor_side1", 8, 1, true),
//   anim("respawn_anchor_side2", 8, 1, true),
//   anim("respawn_anchor_side3", 8, 1, true),
];
